# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "abc"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT
template: "simple"

test1: "~*template*~"
test2: "~*engines.template_toolkit.encoding*~!!OK"
data:
    dir: "~*appdir*~/data"
    currency_csv_file: "~*data.dir*~/currencies.csv"
    industry_csv_file: "~*data.dir*~/industries.csv"
    standand_fields: "~*data.dir*~/standard_fields.csv"
    hybrid_cache:
        dir: "~*data.dir*~/hybrid_cache"
        all_locations: "~*data.hybrid_cache.dir*~/all_locations"

