---
abstract: 'DancerX Config'
author:
  - 'Michael Vu <email@michael.vu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DancerX-Config
requires:
  Cwd: 3.40
  Dancer: 1.3110
  Data::Dumper: 2.131
  FindBin: 1.49
  Template::Simple: 0.06
version: 0.05
